Misc fixes in libc++ for gcc4.8
1. Simplified __gxx__cxx_access_control_sfinae and __gxx__cxx_rtti
   otherwise g++ complains no operand after '!' if
   _LIBCPP_HAS_NO_TRAILING_RETURN isn't defined, for example
2. Make public "MoveOnly(const MoveOnly&);" and "Emplaceable(const Emplaceable&);"
   in tests headers for gcc4.8 which complains both are private for
   16 tests in containers/associative/*map* and containers/unord/unord.*map/
3. Fixed float_h_pass.cpp about missing FLT_EVAL_METHOD and DECIMAL_DIG, where
   gcc does define but with leading and trailing "__".
4. Fixed stdbool_h.pass.cpp about pre-defined bool/true/false

After this CL, testing result for gcc4.8 is comparable to clang3.4
except in the following area:

1. 42 fails in atomics/ because gcc4.8 doesn't support _Atomic
2. 4 fails on "no matching function for call to 'Deleter::Deleter(Deleter)'"
     utilities/memory/unique.ptr/unique.ptr.runtime/unique.ptr.runtime.ctor/default02.pass.cpp
     utilities/memory/unique.ptr/unique.ptr.runtime/unique.ptr.runtime.ctor/pointer02.pass.cpp
     utilities/memory/unique.ptr/unique.ptr.single/unique.ptr.single.ctor/default02.pass.cpp
     utilities/memory/unique.ptr/unique.ptr.single/unique.ptr.single.ctor/pointer02.pass.cpp
     .../include/c++/4.8/type_traits:845:87: error: no matching function for call to 'Deleter::Deleter(Deleter)'
	  sizeof(__is_convertible_imp::__test<_T2>(__is_convertible_imp::__source<_T1>())) == 1
3. 3 fails on "use of deleted function"
     thread/futures/futures.async/async.pass.cpp
     utilities/utility/pairs/pairs.pair/rv_pair_U_V.pass.cpp
     utilities/utility/pairs/pairs.spec/make_pair.pass.cpp
      .../include/c++/4.8/type_traits:845:87: error:
         use of deleted function 'constexpr std::__1::unique_ptr<int>::unique_ptr(const std::__1::unique_ptr<int>&)'
          sizeof(__is_convertible_imp::__test<_T2>(__is_convertible_imp::__source<_T1>())) == 1

4. 16 fails on static_assert() for various reasons
     thread/futures/futures.overview/launch.pass.cpp
     utilities/meta/meta.rel/is_convertible.pass.cpp
     utilities/meta/meta.trans/meta.trans.other/underlying_type.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_literal_type.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_nothrow_assignable.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_nothrow_copy_constructible.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_nothrow_destructible.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_nothrow_move_constructible.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivialially_copyable.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivially_assignable.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivially_copy_assignable.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivially_copy_constructible.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivially_move_assignable.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivially_move_constructible.pass.cpp
     utilities/meta/meta.unary/meta.unary.prop/is_trivial.pass.cpp
     utilities/utility/pairs/pairs.pair/copy_ctor.pass.cpp

5. 4 fails with -O2 (-O0 works; clang3.4 works fine in both -O2 and -O0)
     containers/sequences/forwardlist/forwardlist.modifiers/insert_after_range.pass.cpp
       I/DEBUG   (   51): Abort message: 'insert_after_range.pass.cpp:37: int main(): assertion "distance(c.begin(), c.end()) == 3" failed'
     containers/sequences/list/list.ops/merge_comp.pass.cpp
       I/DEBUG   (   51): Abort message: 'merge_comp.pass.cpp:29: int main(): assertion "c1 == std::list<int>(a3, a3+sizeof(a3)/sizeof(a3[0]))" failed'
     containers/sequences/list/list.ops/merge.pass.cpp
       I/DEBUG   (   51): Abort message: 'merge.pass.cpp:28: int main(): assertion "c1 == std::list<int>(a3, a3+sizeof(a3)/sizeof(a3[0]))" failed'
     iterators/predef.iterators/insert.iterators/front.insert.iter.ops/front.insert.iter.op=/lv_value.pass.cpp
       I/DEBUG   (   51): Abort message: 'lv_value.pass.cpp:28: void test(C) [with C = std::__1::list<Copyable>]: assertion "c.front() == v" failed'

Change-Id: Iae14f979580bf236fc58de09b57a560a1d159205