Fix make-standalone-toolchain.sh --stl=libc++ to run from non-ndk directory
Error message reads:
  ERROR: Can't copy from non-directory: sources/android/support/include

See b.android.com/67690

Change-Id: Iad55ddcfc629c99948aa03bda773bc40bcfee540

Conflicts:
	build/tools/make-standalone-toolchain.sh