Add libc++ *pass.cpp tests in ndk-build build system
1. Only *.pass.cpp tests (4397 in total) are added.
   *.fail.cpp tests (248 in total) will be added later
   because current run-tests.sh only handle single fail
2. All except for the following tests can't be compiled (
   which are commented out)
    all: utilities/meta/meta.trans/meta.trans.other/aligned_storage.pass.cpp
         error message:
           static_assert(std::alignment_of<T1>::value == 16, "");
           static_assert(std::alignment_of<T1>::value == 16, "");
           static_assert(sizeof(T1) == 32, "");

    x86: language.support/support.types/max_align_t.pass.cpp
         error message:
           max_align_t.pass.cpp:22:5: error: static_assert failed "std::alignment_of<std::max_align_t>::value >=
              std::alignment_of<long long>::value"
	          static_assert((std::alignment_of<std::max_align_t>::value >=

3. Add enough symlink to rename file/path with '=' (replace it with 'EQ')

Change-Id: I8d90f1ac242ddbc0ed34e766c0ed1280cb0ee789