Update mingw64 version to svn@5861
Required to build gcc-4.8 64-bit toolchain. Otherwise got:
x86_64-w64-mingw32/include/msxml.h:637:38:
error: macro "abort" passed 1 arguments, but takes just 0

Change-Id: I10c6dbf5829892bdce22b697e30809f37c5dd751
Signed-off-by: Pavel Chupin <pavel.v.chupin@intel.com>