ndk-gdb.py: move start_gdb to top level.
multiprocessing on Windows is unhappy with start_gdb being in a local
scope:

    pickle.PicklingError: Can't pickle <function start_jdb at 0x02973970>: it's not found as __main__.start_jdb

Bug: https://github.com/android-ndk/ndk/issues/46
Change-Id: Id0e9eaa05393b7451b3dcdfa21242bc82529414e
(cherry picked from commit 362ecc9c2404d0cd602689ba87d60fadbd43c511)