Add libc++ *pass.cpp tests in ndk-build build system
1. Only *.pass.cpp tests (4397 in total) are added.
   *.fail.cpp tests (248 in total) will be added later
   because current run-tests.sh only handle single fail
2. All except for the following tests can't be compiled (
   which are commented out)
    all: utilities/meta/meta.trans/meta.trans.other/aligned_storage.pass.cpp
         error message:
           static_assert(std::alignment_of<T1>::value == 16, "");
           static_assert(std::alignment_of<T1>::value == 16, "");
           static_assert(sizeof(T1) == 32, "");

    x86: language.support/support.types/max_align_t.pass.cpp
         error message:
           max_align_t.pass.cpp:22:5: error: static_assert failed "std::alignment_of<std::max_align_t>::value >=
              std::alignment_of<long long>::value"
	          static_assert((std::alignment_of<std::max_align_t>::value >=
    gcc4.8:
         thread/futures/futures.async/async.pass.cpp
         thread/futures/futures.overview/launch.pass.cpp
         utilities/memory/unique.ptr/unique.ptr.runtime/unique.ptr.runtime.ctor/default02.pass.cpp
         utilities/memory/unique.ptr/unique.ptr.runtime/unique.ptr.runtime.ctor/pointer02.pass.cpp
         utilities/memory/unique.ptr/unique.ptr.single/unique.ptr.single.ctor/default02.pass.cpp
         utilities/memory/unique.ptr/unique.ptr.single/unique.ptr.single.ctor/pointer02.pass.cpp
         utilities/meta/meta.rel/is_convertible.pass.cpp
         utilities/meta/meta.trans/meta.trans.other/underlying_type.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_literal_type.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_nothrow_assignable.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_nothrow_copy_constructible.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_nothrow_destructible.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_nothrow_move_constructible.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivially_assignable.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivially_copy_assignable.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivially_copy_constructible.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivially_move_assignable.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivially_move_constructible.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivial.pass.cpp
         utilities/utility/pairs/pairs.pair/copy_ctor.pass.cpp
         utilities/meta/meta.unary/meta.unary.prop/is_trivialially_copyable.pass.cpp

    clang3.3
         utilities/meta/meta.unary/meta.unary.prop/is_trivialially_copyable.pass.cpp

3. Add enough symlink to rename file/path with '=' (replace it with 'EQ')

Change-Id: I8d90f1ac242ddbc0ed34e766c0ed1280cb0ee789